// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCAXvutdBiJhxDUBZdhiImaGIyKpuIKdA',
    appId: '1:345674744115:web:1e691774cee3b2f865be46',
    messagingSenderId: '345674744115',
    projectId: 'todoapp-5c9d8',
    authDomain: 'todoapp-5c9d8.firebaseapp.com',
    storageBucket: 'todoapp-5c9d8.firebasestorage.app',
    measurementId: 'G-REN72DSM5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQWUkonCJvstXEefCY_rw8APEQgpygWJA',
    appId: '1:345674744115:android:3200d3fb3bd522a965be46',
    messagingSenderId: '345674744115',
    projectId: 'todoapp-5c9d8',
    storageBucket: 'todoapp-5c9d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnL0Kut-Dvn9-E-KaIXeP6pMhrB90kmmA',
    appId: '1:345674744115:ios:2c640f45f5c119bf65be46',
    messagingSenderId: '345674744115',
    projectId: 'todoapp-5c9d8',
    storageBucket: 'todoapp-5c9d8.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnL0Kut-Dvn9-E-KaIXeP6pMhrB90kmmA',
    appId: '1:345674744115:ios:2c640f45f5c119bf65be46',
    messagingSenderId: '345674744115',
    projectId: 'todoapp-5c9d8',
    storageBucket: 'todoapp-5c9d8.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCAXvutdBiJhxDUBZdhiImaGIyKpuIKdA',
    appId: '1:345674744115:web:52cef94091ea5cc765be46',
    messagingSenderId: '345674744115',
    projectId: 'todoapp-5c9d8',
    authDomain: 'todoapp-5c9d8.firebaseapp.com',
    storageBucket: 'todoapp-5c9d8.firebasestorage.app',
    measurementId: 'G-Q3WZ55L4ZM',
  );
}
